name: kouyakusu_test
on: [push]
jobs:
  io_test:
    name: kouyakusu error test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Permission Setting
        run: chmod +x kouyakusu.sh test_kouyakusu.sh
      - name: Test Run
        run: ./test_kouyakusu.sh